pipeline {
    agent any

    tools {nodejs "NodeJS"}

    environment {
        PROJECT_PATH="${env.JENKINS_HOME}/workspace/testing-strategy-3/testing-strategy-3/"
        SCRIPTS_PATH="${PROJECT_PATH}/scripts"
        WEB_PATH="${PROJECT_PATH}/web"
        TEST_WEB_PATH="${PROJECT_PATH}/e2e-web"
        DEV="dev"
        ALPHA="alpha"
        PREPROD="preprod"
        PROD="prod"
    }

    stages {
        stage('Build and run web environment DEV') {
           steps {
                dir("${WEB_PATH}") {
                    sh """
                        ls -al && npm install && npm run start &
                    """
                }
            }
        }
        stage('Test E2E web environment DEV') {
            steps {
                dir("${TEST_WEB_PATH}") {
                   sh """
                        npm install && npm run test
                    """
                }
            }
        }
        stage('Deployment') {
            steps {
                dir("${SCRIPTS_PATH}") {
                   sh """
                    echo "Deployment"
                    """
                }
            }
        }
    }
}