pipeline {
    agent any

    tools {nodejs "NodeJS"}

    environment {
        PROJECT_PATH="${env.JENKINS_HOME}/workspace/testing-strategy-3/testing-strategy-3/"
        SCRIPTS_PATH="${PROJECT_PATH}/scripts"
        WEB_PATH="${PROJECT_PATH}/web"
        TEST_WEB_PATH="${PROJECT_PATH}/e2e-web"
        TEST_WEB_REPORT_PATH="${TEST_WEB_PATH}/cypress/cucumber-json"
        DEV="dev"
        ALPHA="alpha"
        PREPROD="preprod"
        PROD="prod"
    }

    stages {
        stage('Build and run web environment DEV') {
           steps {
                dir("${WEB_PATH}") {
                    sh """
                        ls -al && yarn && yarn start &
                    """
                }
            }
        }
        stage('Test E2E web environment DEV') {
            steps {
                dir("${TEST_WEB_PATH}") {
                   sh """
                        yarn && yarn test && yarn generate-report
                    """
                    publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: "${TEST_WEB_REPORT_PATH}", reportFiles: 'index.html', reportName: 'HTML Report', reportTitles: 'Cypress report', useWrapperFileDirectly: true])
                }
            }
            post {
                always {
                    dir("${SCRIPTS_PATH}") {
                   sh """
                        ./application-management.sh close
                    """
                    }
                }
            }
        }
        stage('Deployment') {
            steps {
                dir("${SCRIPTS_PATH}") {
                   sh """
                    echo "Deployment"
                    """
                }
            }
        }
    }
}

// cypress/cucumber-json/index.html